### ISSUE TITLE
Please rectify qiita article

### ISSUE THREAD

**Issue by botika** [Kogia-sima/sailfish#19]
Yarte fixed did one day, https://github.com/TechEmpower/FrameworkBenchmarks/pull/5710#issuecomment-638556866, BEFORE first commit of https://github.com/Kogia-sima/sailfish/commit/08dacdd263f8b4bc56e5358801ba4979d596f912 sailfish.

It seems that I copied the code, when my implementation based on slices is faster. Please fix it.
https://qiita.com/Kogia_sima/items/87157af0fbf50ceda0ae

**Comment by Kogia-sima** [comment]
Actually some initials commit were deleted one day and I've force-pushed a new commit to the master branch because I've found the license issue. That's why the initial commit contains very large change.

However, even so, Yarte 0.9.5 (which is the first release which contains `YarteFixedTrait`) was released at the the almost same time as `sailfish`'s initial commit.
