### ISSUE TITLE
VS Code extension instructions

### ISSUE THREAD

**Issue by peterreeves** [Kogia-sima/sailfish#23]
Hi

I'm confused about how to get the VS Code extension working. I've copied the `syntax/vscode` folder into my VS Code extensions folder, but nothing seems to happen. Is there an install step I need to run?

Alternatively would it be possible to get the extension on the VS Code marketplace, or distribute it a `.vsix` file?

**Comment by Kogia-sima** [comment]
@peterreeves I'm sorry for the inconvenience caused by missing documentation, but since I am a heavy Vim user, I don't know much about VS Code.

In my case, Copying the contents of `syntax/vscode` directory into `~/.vscode/extensions/kogia-sima.vscode-sailfish-0.1.0` directory has worked properly.

I didn't know about .vsix` file. Thanks for the tips! And I'll update the document soon.

**Comment by Kogia-sima** [comment]
The extension is now available at [Marketplace](https://marketplace.visualstudio.com/items?itemName=kogia-sima.vscode-sailfish).

**Comment by peterreeves** [comment]
Thanks for putting it on the marketplace, it works perfectly!
