### ISSUE TITLE
Incorrect buffer in yarte fixed bench

### ISSUE THREAD

**Issue by botika** [Kogia-sima/sailfish#6]
Congratulations first! I'm really enjoying reading your code. I wanted to clarify that yarte fixed is made not to relocate. You can test with the buffer in the example or a` MaybeUninit` since my work has nothing to do with `String` and its relocation algorithm.

The two buffers that should be used are:
https://github.com/botika/yarte/blob/master/example/src/main.rs#L46-L55
```
let mut buf: [u8; SIZE] = unsafe { MaybeUninit::uninit().assume_init() };
let b = unsafe { template.call(&mut buf) }.unwrap();
let _ = buf[..b].to_vec();
```

With these benches you are measuring the speed of your buffer. 
Yarte is abstract about the buffer.

What really is the only way to do faster is re-implement `rep movsb` or buy another computer. Because I don't think you want to re-alloc in a half request
https://github.com/torvalds/linux/blob/master/arch/x86/lib/memcpy_64.S#L56

**Comment by Kogia-sima** [comment]
Thank you for your many feed backs! I would like to appreciate your useful indications :)

However, I can't figure out why I should not use pre-alocated heap data, but my benchmark is going to compare the performance of real world server response.

Also memory pre-allocation is not a hotspot. I've analyzed the framegraph but memory pre-allocation is a tiny overhead compared to rendering content.

In addition, since `[u8; N]` data is placed at the stack memory, `<[u8; N]>::to_vec` method **always** allocate a new memory and copy the internal data. It is inefficient in real world server response. In contrast, there is a guarentee that `std::string::String` has always its own data in heap memory. That's why you should pre-allocate the memory on the heap. When converting `String` into `bytes::Bytes` the heap data is [shrinked](https://docs.rs/bytes/0.5.4/src/bytes/bytes.rs.html#765-796), but in most cases shrinking a heap data does not relocate any data.

Furthermore, using too large stack may causes stack overflow. You should not use stack if you want to render the very large JSON/JavaScript data.By using heap you can not only render those contents but deside the pre-allocation size dynamically.

> Yarte is abstract about the buffer.

Year it's true. However, in many web frameworks in Rust ([Actix web](https://github.com/actix/actix-web), [Iron](https://github.com/iron/iron), etc.), `String`/`Vec<u8>` type can be converted directly into the response data. That's why I use `String` to measure the `Yarte` performance.

-----

If you think my benchmark is unfair, please clarify (1) which part of my code should be fixed, (2) why it is unfair compared to another benchmarks and (3) what situations you are going to compare the performance of.

**Comment by botika** [comment]
For network, multi thread, I use `bytes` crate. And single thread I use `std::mem::MaybeUninit`. 

I do the same as you, write over `layout`, only my layout is static.

You don't need to compare it, I just do an `if` and `memcpy` and `slice` is a `pointer` and a `len`. And I deal with the cases where `memcpy` is less efficient.

If I do not convince you that in terms of buffers everything is already done, look at `bytes` crates and who did it and who uses it.

**Comment by Kogia-sima** [comment]
> I just do an if and memcpy and slice is a pointer and a len. And I deal with the cases where memcpy is less efficient.

The number of operations for rendering contents is almost nothing to do with which the buffer memory is on the heap or stack. The only difference is that compiler can calculate the memory address to be written at compile time.

In contrast, calling `to_vec` always copy all data into a heap. That is inefficient.

> If I do not convince you that in terms of buffers everything is already done, look at bytes crates and who did it and who uses it.

If you are going to convert the results into `bytes::Bytes`, just use `String` or `bytes::BytesMut`. Converting `String`/`BytesMut` into `Bytes` does not copy the data, and thus is more efficient than calling `to_vec`.

**Comment by botika** [comment]
Sorry I don't see `to_vec` in my comment. **Not use `to_vec` in production**, it's only for my benchmark. In my benchmark I look at how long it takes to heap, it is mandatory to upload it to heap, it is to standardize the bench. Sorry I didn't know what you were saying.

**Comment by Kogia-sima** [comment]
> Sorry I don't see to_vec in my comment. Not use to_vec in production, it's only for my benchmark. In my benchmark I look at how long it takes to heap, it is mandatory to upload it to heap, it is to standardize the bench. Sorry I didn't know what you were saying.

That's my fault. I'm sorry for misunderstanding your suggestion. I sent a review comment.

**Comment by botika** [comment]
I don't see any new comments in the PR.

**Comment by botika** [comment]
Someone opened an issue that will also interest you :smiley_cat:  : https://github.com/botika/v_escape/blob/master/v_escape/src/ranges/avx.rs#L66-L82

**Comment by Kogia-sima** [comment]
@botika 
https://github.com/Kogia-sima/sailfish/pull/12/files/86658d4a96d3d7845fff00f100f998a2a83334de#r439707725
